apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: sy07
        url: https://kubernetes.default.svc
      - cluster: sy08
        url: https://api.sy08.cloudcitst.shoot.canary.k8s-hana.ondemand.com
  template:
    metadata:
      name: '{{cluster}}-myapp'
    spec:
      project: default
      source:
        repoURL: https://github.com/syurevich/argocd-app-config.git
        targetRevision: HEAD
        path: clusters/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: myappdev
      syncPolicy:
        syncOptions:
        - CreateNamespace=true

        automated:
          selfHeal: true
          prune: true


